version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: referrer
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025